# Generated by nixos-generate-config on Forge. Regenerate on the machine if the disk layout changes.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];
  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/24d2ef0f-43ce-4f4d-bf7d-b0b824d8a008";
    fsType = "btrfs";
  };
  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/24d2ef0f-43ce-4f4d-bf7d-b0b824d8a008";
    fsType = "btrfs";
    options = ["subvol=home"];
  };
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/24d2ef0f-43ce-4f4d-bf7d-b0b824d8a008";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9435-E33E";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };
  swapDevices = [{device = "/dev/disk/by-uuid/a997b4f6-abfd-4d24-8482-df6395531440";}];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
